using System.ComponentModel;

namespace ActionCalculator.Models
{
    public enum StarPlayer
    {
        [Description("Akhorne the Squirrel")]              AkhorneTheSquirrel = 1,
        [Description("Anqi Panqi")]                        AnqiPanqi,
        [Description("Barik Farblast")]                    BarikFarblast,
        [Description("Bilerot Vomitflesh")]                BilerotVomitflesh,
        [Description("Boa Kon'ssstriktr")]                 BoaKonssstriktr,
        [Description("Bomber Dribblesnot")]                BomberDribblesnot,
        [Description("Captain Karina von Riesz")]          CaptainKarinaVonRiesz,
        [Description("Cindy Piewhistle")]                  CindyPiewhistle,
        [Description("Count Luthor von Drakenborg")]       CountLuthorVonDrakenborg,
        [Description("Crumbleberry")]                      Crumbleberry,
        [Description("Dribl")]                             Dribl,
        [Description("Drull")]                             Drull,
        [Description("Eldril Sidewinder")]                 EldrilSidewinder,
        [Description("Estelle la Veneaux")]                EstelleLaVeneaux,
        [Description("Frank 'N' Stein")]                   FrankNStein,
        [Description("Fungus the Loon")]                   FungusTheLoon,
        [Description("Glart Smarshrip")]                   GlartSmarshrip,
        [Description("Gloriel Summerbloom")]               GlorielSummerbloom,
        [Description("Glotl Stop")]                        GlotlStop,
        [Description("Grak")]                              Grak,
        [Description("Grashnak Blackhoof")]                GrashnakBlackhoof,
        [Description("Gretchen Wächter")]                  GretchenWachter,
        [Description("Griff Oberwald")]                    GriffOberwald,
        [Description("Grombrindal, the White Dwarf")]      GrombrindaTheWhiteDwarf,
        [Description("Guffle Pusmaw")]                     GufflePusmaw,
        [Description("H'thark The Unstoppable")]           HtharkTheUnstoppable,
        [Description("Hakflem Skuttlespike")]              HakflemSkuttlespike,
        [Description("Helmut Wulf")]                       HelmutWulf,
        [Description("Ivan 'the Animal' Deathshroud")]     IvanTheAnimalDeathshroud,
        [Description("Ivar Eriksson")]                     IvarEriksson,
        [Description("Jeremiah Kool")]                     JeremiahKool,
        [Description("Jordell Freshbreeze")]               JordellFreshbreeze,
        [Description("Josef Bugman")]                      JosefBugman,
        [Description("Karla Von Kill")]                    KarlaVonKill,
        [Description("Kiroth Krakeneye")]                  KirothKrakeneye,
        [Description("Kreek, \"The Verminator\" Rustgouger")] KreekTheVerminatorRustgouger,
        [Description("Lord Borak")]                        LordBorak,
        [Description("Lucien Swift")]                      LucienSwift,
        [Description("Max Spleenripper")]                  MaxSpleenripper,
        [Description("Mighty Zug")]                        MightyZug,
        [Description("Morg 'n' Thorg")]                    MorgNThorg,
        [Description("Nobbla Blackwart")]                  NobblaBlackwart,
        [Description("Puggy Baconbreath")]                 PuggyBaconbreath,
        [Description("Rashnack Backstabber")]              RashnackBackstabber,
        [Description("Ripper Bolgrot")]                    RipperBolgrot,
        [Description("Roxanna Darknail")]                  RoxannaDarknail,
        [Description("Rumbelow Sheepskin")]                RumbelowSheepskin,
        [Description("Scyla Anfingrimm")]                  ScylaAnfingrimm,
        [Description("Scrappa Sorehead")]                  ScrappaSorehead,
        [Description("Skitter Stab-Stab")]                 SkitterStabStab,
        [Description("Skrorg Snowpelt")]                   SkrorgSnowpelt,
        [Description("Skrull Halfheight")]                 SkrullHalfheight,
        [Description("The Black Gobbo")]                   TheBlackGobbo,
        [Description("Thorsson Stoutmead")]                ThorssonStoutmead,
        [Description("Valen Swift")]                       ValenSwift,
        [Description("Varag Ghoul-Chewer")]                VaragGhoulChewer,
        [Description("Wilhelm Chaney")]                    WilhelmChaney,
        [Description("Withergrasp Doubledrool")]           WithergraspDoubledrool,
        [Description("Zolcath the Zoat")]                  ZolcathTheZoat,
    }
}
