namespace ActionCalculator.Models
{
    public static class StarPlayerRules
    {
        public static IReadOnlyList<StarPlayerRule> All { get; } = new StarPlayerRule[]
        {
            new("Akhorne the Squirrel",         "Blind Rage",                   "Akhorne may re-roll the D6 when rolling for the Dauntless skill.",                                                                                                                                                                                                        StarPlayerSkill.BlindRage,              ["Claws", "Dauntless", "Dodge", "Frenzy", "Jump Up", "Loner (4+)", "No Ball", "Sidestep", "Stunty", "Titchy"]),
            new("Anqi Panqi",                   "Savage Blow",                  "Once per game, when Anqi performs a Block, he may re-roll any number of the Block dice.",                                                                                                                                                                                 StarPlayerSkill.SavageBlow,             ["Block", "Grab", "Loner (4+)", "Stand Firm", "Unsteady"]),
            new("Barik Farblast",               "Blast It!",                    "Whenever Barik makes a Hail Mary Pass, he may re-roll any Scatter results to determine where the ball lands. Team-mates attempting to catch also gain +1 to the roll.",                                                                                                   StarPlayerSkill.BlastIt,                ["Cannoneer", "Hail Mary Pass", "Loner (4+)", "Pass", "Secret Weapon", "Sure Hands", "Thick Skull"]),
            new("Bilerot Vomitflesh",           "Putrid Regurgitation",         "Once per half, Bilerot may use Projectile Vomit as a Special Action. This can be used even if he has already performed a Block this turn.",                                                                                                                               StarPlayerSkill.PutridRegurgitation,    ["Dirty Player", "Disturbing Presence", "Foul Appearance", "Lone Fouler", "Loner (4+)", "Regeneration", "Unsteady"]),
            new("Boa Kon'ssstriktr",            "Look Into My Eyes",            "Once per game, if Boa starts his activation Marking an opponent carrying the ball, roll a D6. On a 2+ Boa steals the ball and his activation immediately ends.",                                                                                                          StarPlayerSkill.LookIntoMyEyes,         ["Dodge", "Fend", "Hypnotic Gaze", "Loner (4+)", "Prehensile Tail", "Safe Pair Of Hands", "Sidestep"]),
            new("Bomber Dribblesnot",           "Kaboom!",                      "No description available.",                                                                                                                                                                                                                                               StarPlayerSkill.Kaboom,                 ["Accurate", "Bombardier", "Dodge", "Loner (4+)", "Right Stuff", "Secret Weapon", "Stunty"]),
            new("Captain Karina von Riesz",     "Tasty Morsel",                 "Once per game, when Karina fails a Bloodlust roll, she may bite an opposition player with ST 3 or lower as if they were a Thrall team-mate. Cannot target Star Players.",                                                                                                 StarPlayerSkill.TastyMorsel,            ["Bloodlust (2+)", "Dodge", "Hypnotic Gaze", "Jump Up", "Loner (4+)", "Regeneration"]),
            new("Cindy Piewhistle",             "All You Can Eat",              "Once per game, Cindy may throw two Bombs instead of one, committing to both before the first throw. After the second, roll a D6: on a 1, 2 or 3 Cindy is immediately Sent-off.",                                                                                         StarPlayerSkill.AllYouCanEat,           ["Accurate", "Bombardier", "Dodge", "Loner (4+)", "Secret Weapon", "Stunty"]),
            new("Count Luthor von Drakenborg",  "Star of the Show",             "Once per game, when Count Luthor scores a Touchdown, his coach gains one Team Re-roll valid until end of the following Drive. Unused re-rolls are lost.",                                                                                                                  StarPlayerSkill.StarOfTheShow,          ["Block", "Hypnotic Gaze", "Loner (4+)", "Regeneration", "Sidestep"]),
            new("Crumbleberry",                 "I'll Carry You",               "Must be hired as a pair. Once per half, if Grak begins activation adjacent to Crumbleberry, Grak may carry Crumbleberry. Remove Crumbleberry from the pitch and place Crumbleberry in an adjacent empty square at the end of Grak's activation.",                        StarPlayerSkill.IllCarryYou,            ["Dodge", "Lethal Flight", "Loner (4+)", "Right Stuff", "Stunty", "Sure Hands"]),
            new("Dribl",                        "A Sneaky Pair",                "Must be hired alongside Drull. Whenever either Dribl or Drull fouls or Stabs an opponent who is Marked by both of them, they gain +1 to the roll.",                                                                                                                      StarPlayerSkill.ASneakyPair,            ["Dirty Player", "Dodge", "Loner (4+)", "Quick Foul", "Sidestep", "Sneaky Git", "Stunty"]),
            new("Drull",                        "A Sneaky Pair",                "Must be hired alongside Dribl. Whenever either Dribl or Drull fouls or Stabs an opponent who is Marked by both of them, they gain +1 to the roll.",                                                                                                                      StarPlayerSkill.ASneakyPair,            ["Dodge", "Loner (4+)", "Sidestep", "Stab", "Stunty"]),
            new("Eldril Sidewinder",            "Mesmerising Dance",            "Once per half, Eldril may re-roll the dice when performing a Hypnotic Gaze.",                                                                                                                                                                                             StarPlayerSkill.MesmerisingDance,       ["Catch", "Dodge", "Hypnotic Gaze", "Loner (4+)", "Nerves Of Steel", "On The Ball"]),
            new("Estelle la Veneaux",           "Baleful Hex",                  "Once per game at the start of her activation, Estelle picks an opponent within 5 squares and rolls a D6. On a 2+ that player becomes Distracted and cannot be activated during the opponent's next turn.",                                                                StarPlayerSkill.BalefulHex,             ["Disturbing Presence", "Dodge", "Guard", "Loner (4+)", "Sidestep"]),
            new("Frank 'N' Stein",              "Brutal Block",                 "No description available.",                                                                                                                                                                                                                                               StarPlayerSkill.BrutalBlock,            ["Break Tackle", "Loner (4+)", "Mighty Blow", "Regeneration", "Stand Firm", "Thick Skull"]),
            new("Fungus the Loon",              "Whirling Dervish!",            "Once per activation, Fungus may re-roll the direction die that determines his Ball & Chain movement.",                                                                                                                                                                    StarPlayerSkill.WhirlingDervish,        ["Ball & Chain", "Loner (4+)", "Mighty Blow", "No Ball", "Secret Weapon", "Stunty"]),
            new("Glart Smarshrip",              "Frenzied Rush",                "Once per half, when Glart declares a Blitz he gains Frenzy for that activation. He cannot use Grab in the same turn he uses this rule.",                                                                                                                                 StarPlayerSkill.FrenziedRush,           ["Block", "Claws", "Grab", "Juggernaut", "Loner (4+)", "Stand Firm"]),
            new("Gloriel Summerbloom",          "Shot to Nothing",              "Once per game, Gloriel gains the Hail Mary Pass skill for the duration of her activation.",                                                                                                                                                                               StarPlayerSkill.ShotToNothing,          ["Accurate", "Dodge", "Loner (3+)", "Pass", "Sidestep", "Sure Hands"]),
            new("Glotl Stop",                   "Primal Savagery",              "Once per game, when Glotl fails an Animal Savagery roll, he may redirect his lash-out to an opposition player instead of a team-mate.",                                                                                                                                  StarPlayerSkill.PrimalSavagery,         ["Animal Savagery", "Frenzy", "Loner (4+)", "Mighty Blow", "Prehensile Tail", "Stand Firm", "Thick Skull"]),
            new("Grak",                         "I'll Carry You",               "Must be hired as a pair. Once per half, if Grak begins activation adjacent to Crumbleberry, Grak may carry Crumbleberry. Remove Crumbleberry from the pitch and place Crumbleberry in an adjacent empty square at the end of Grak's activation.",                        StarPlayerSkill.IllCarryYou,            ["Bone Head", "Kick Team-mate", "Loner (4+)", "Mighty Blow", "Thick Skull"]),
            new("Grashnak Blackhoof",           "Gored by the Bull",            "Once per game, when Grashnak Blitzes, he may roll one extra Block die against the target regardless of ST (maximum three total). If Frenzy triggers a second Block, that Block also benefits.",                                                                           StarPlayerSkill.GoredByTheBull,         ["Frenzy", "Horns", "Loner (4+)", "Mighty Blow", "Thick Skull", "Unchannelled Fury"]),
            new("Gretchen Wächter",             "Incorporeal",                  "Once per game, for the rest of her activation Gretchen does not need to make Dodge rolls when leaving an opposition Tackle Zone.",                                                                                                                                        StarPlayerSkill.Incorporeal,            ["Disturbing Presence", "Dodge", "Foul Appearance", "Jump Up", "Loner (4+)", "No Ball", "Regeneration", "Shadowing", "Sidestep"]),
            new("Griff Oberwald",               "Consummate Professional",      "Once per game, apply a +1 modifier to any Agility test Griff has rolled. This can be applied after seeing the roll's result.",                                                                                                                                           StarPlayerSkill.ConsummateProfessional, ["Block", "Dodge", "Fend", "Loner (3+)", "Sprint", "Sure Feet"]),
            new("Grombrindal, the White Dwarf", "Wisdom of the White Dwarf",    "Once per game when activated, Grombrindal grants a team-mate within 2 squares one of the following skills until end of turn: Break Tackle, Dauntless, Mighty Blow, or Sure Feet.",                                                                                       StarPlayerSkill.WisdomOfTheWhiteDwarf,  ["Block", "Break Tackle", "Dauntless", "Loner (4+)", "Mighty Blow", "Stand Firm", "Sure Feet", "Thick Skull"]),
            new("Guffle Pusmaw",                "Quick Bite",                   "Once per game, if an opponent Guffle is Marking catches the ball, Guffle may immediately make an Armour roll against them. If the armour breaks, Guffle takes possession. No Turnover is caused.",                                                                        StarPlayerSkill.QuickBite,              ["Foul Appearance", "Loner (4+)", "Monstrous Mouth", "Nerves Of Steel", "On The Ball", "Plague Ridden"]),
            new("H'thark The Unstoppable",      "Unstoppable Momentum",         "When H'thark performs a Block as part of a Blitz, he may re-roll one Block die.",                                                                                                                                                                                        StarPlayerSkill.UnstoppableMomentum,    ["Block", "Break Tackle", "Defensive", "Juggernaut", "Loner (4+)", "Sprint", "Sure Feet", "Thick Skull", "Unsteady"]),
            new("Hakflem Skuttlespike",         "Treacherous",                  "Once per game, if Hakflem is activated adjacent to a team-mate carrying the ball, he may steal it. The team-mate is immediately knocked down. This does not cause a Turnover even if a Casualty results.",                                                                StarPlayerSkill.Treacherous,            ["Dodge", "Extra Arms", "Loner (4+)", "Prehensile Tail", "Two Heads"]),
            new("Helmut Wulf",                  "Old Pro",                      "Once per game, Helmut may use his Pro skill to re-roll a single die from an Armour roll. Pro's usual restrictions still apply.",                                                                                                                                          StarPlayerSkill.OldPro,                 ["Chainsaw", "Loner (4+)", "No Ball", "Pro", "Secret Weapon", "Stand Firm"]),
            new("Ivan 'the Animal' Deathshroud","Dwarfen Scourge",              "Once per game, when Ivan knocks down an opponent with a Block, gain +1 to the Armour or Injury roll. Against Dwarf players, this bonus is +2 instead. Can be applied after the roll.",                                                                                   StarPlayerSkill.DwarfenScourge,         ["Block", "Disturbing Presence", "Hatred (Dwarf)", "Juggernaut", "Loner (4+)", "Regeneration", "Strip Ball", "Tackle"]),
            new("Ivar Eriksson",                "Raiding Party",                "Once per Drive at the start of his activation, Ivar may move one Open team-mate within 5 squares 1 square, so long as they end that move Marking an opponent.",                                                                                                          StarPlayerSkill.RaidingParty,           ["Block", "Guard", "Loner (4+)", "Tackle"]),
            new("Jeremiah Kool",                "The Flashing Blade",           "Once per game at activation start, Jeremiah may Stab an opponent he is Marking, then follow up with a Move action before his activation ends.",                                                                                                                          StarPlayerSkill.TheFlashingBlade,       ["Block", "Diving Catch", "Dodge", "Dump-Off", "Loner (4+)", "Nerves Of Steel", "On The Ball", "Pass", "Sidestep"]),
            new("Jordell Freshbreeze",          "Swift as the Breeze",          "Once per game, Jordell may automatically pass a Dodge, Leap, or Rush test on a 2+ regardless of any modifiers.",                                                                                                                                                         StarPlayerSkill.SwiftAsTheBreeze,       ["Block", "Diving Catch", "Dodge", "Leap", "Loner (4+)", "Sidestep", "Steady Footing"]),
            new("Josef Bugman",                 "Dwarfen Grit",                 "Once per game, when Josef's armour is broken by an Armour roll, re-roll that Armour roll.",                                                                                                                                                                               StarPlayerSkill.DwarfenGrit,            ["Block", "Drunkard", "Fend", "Loner (3+)", "Tackle", "Taunt", "Thick Skull"]),
            new("Karla Von Kill",               "Indomitable",                  "Once per game, when Karla successfully activates Dauntless, she may increase her ST to double the target's ST for that Block.",                                                                                                                                           StarPlayerSkill.Indomitable,            ["Block", "Dauntless", "Dodge", "Jump Up", "Loner (4+)"]),
            new("Kiroth Krakeneye",             "Black Ink",                    "Once per game at the start of an activation, Kiroth Distracts an opponent he is Marking. That player stays Distracted until they are next activated.",                                                                                                                    StarPlayerSkill.BlackInk,               ["Disturbing Presence", "Foul Appearance", "Loner (4+)", "On The Ball", "Tackle", "Tentacles"]),
            new("Kreek, \"The Verminator\" Rustgouger", "I'll Be Back!",        "The first time Kreek would be Sent-off for Secret Weapon, he stays on the pitch instead. His coach may not Argue the Call when this rule activates.",                                                                                                                     StarPlayerSkill.IllBeBack,              ["Ball & Chain", "Loner (4+)", "Mighty Blow", "No Ball", "Prehensile Tail", "Secret Weapon"]),
            new("Lord Borak",                   "Lord of Chaos",                "Once per game, re-roll one Block die when Lord Borak performs a Block action.",                                                                                                                                                                                           StarPlayerSkill.LordOfChaos,            ["Block", "Dirty Player", "Leader", "Loner (3+)", "Mighty Blow", "Put the Boot In", "Sneaky Git"]),
            new("Lucien Swift",                 "Working in Tandem",            "Must be hired alongside Valen Swift. If Lucien blocks an opponent who is also Marked by Valen, Lucien may re-roll one Block die.",                                                                                                                                        StarPlayerSkill.WorkingInTandem,        ["Block", "Loner (4+)", "Mighty Blow", "Tackle"]),
            new("Max Spleenripper",             "Maximum Carnage",              "Once per game, after performing a Chainsaw Attack, Max may immediately make another Chainsaw Attack against a different opponent.",                                                                                                                                        StarPlayerSkill.MaximumCarnage,         ["Chainsaw", "Loner (4+)", "No Ball", "Secret Weapon"]),
            new("Mighty Zug",                   "Crushing Blow",                "Once per game, when Zug knocks down an opponent with a Block, gain +1 to the Armour roll. Can be applied after the roll.",                                                                                                                                               StarPlayerSkill.CrushingBlow,           ["Block", "Loner (4+)", "Mighty Blow", "Unsteady"]),
            new("Morg 'n' Thorg",               "The Ballista",                 "Once per game, Morg may re-roll the Passing Ability test for a Throw Team-mate action.",                                                                                                                                                                                 StarPlayerSkill.TheBallista,            ["Block", "Bullseye", "Hatred (Undead)", "Loner (4+)", "Mighty Blow", "Thick Skull", "Throw Team-mate"]),
            new("Nobbla Blackwart",             "Kick 'em While They're Down!", "Once per game, Nobbla may use the Chainsaw Attack against a Prone or Stunned opponent. This is not a Foul action, so he cannot be Sent-off for it.",                                                                                                                      StarPlayerSkill.KickEmWhileTheyreDown, ["Block", "Chainsaw", "Dodge", "Loner (4+)", "No Ball", "Saboteur", "Secret Weapon", "Stunty"]),
            new("Puggy Baconbreath",            "Halfling Luck",                "Once per game, re-roll any single die or one die from a multi-die roll. Cannot be used on Armour, Injury, or Casualty rolls.",                                                                                                                                           StarPlayerSkill.HalflingLuck,           ["Block", "Dodge", "Loner (3+)", "Nerves Of Steel", "Right Stuff", "Stunty"]),
            new("Rashnack Backstabber",         "Toxin Connoisseur",            "Once per game, when Rashnak breaks an opponent's armour with a Stab, gain +1 to the Injury roll. Can be applied after the roll.",                                                                                                                                        StarPlayerSkill.ToxinConnoisseur,       ["Loner (4+)", "Shadowing", "Sidestep", "Sneaky Git", "Stab"]),
            new("Ripper Bolgrot",               "Thinking Man's Troll",         "Once per half, re-roll any single die or one die from a multi-die roll. Cannot be used on Armour, Injury, or Casualty rolls.",                                                                                                                                          StarPlayerSkill.ThinkingMansTroll,      ["Bullseye", "Grab", "Loner (4+)", "Mighty Blow", "Regeneration", "Throw Team-mate"]),
            new("Roxanna Darknail",             "Slashing Nails",               "Once per half, when Roxanna declares a Blitz, she gains Claws for that activation.",                                                                                                                                                                                     StarPlayerSkill.SlashingNails,          ["Dodge", "Frenzy", "Jump Up", "Juggernaut", "Leap", "Loner (4+)"]),
            new("Rumbelow Sheepskin",           "Ram",                          "Once per game, when Rumbelow knocks down an opponent with a Block, gain +1 to either the Armour or Injury roll. Can be applied after the roll.",                                                                                                                          StarPlayerSkill.Ram,                    ["Block", "Horns", "Juggernaut", "Loner (4+)", "Tackle", "Thick Skull"]),
            new("Scyla Anfingrimm",             "Fury of the Blood God",        "Once per game, if Scyla rolls a 1 on his Unchannelled Fury check after declaring a Block, he may instead perform two Block actions. The first must be fully resolved (including Frenzy) before the second.",                                                              StarPlayerSkill.FuryOfTheBloodGod,     ["Claws", "Frenzy", "Loner (4+)", "Mighty Blow", "Prehensile Tail", "Thick Skull", "Unchannelled Fury"]),
            new("Scrappa Sorehead",             "Yoink!",                       "Once per game, when Scrappa attempts an Interception, roll a D6. On a 2+ he automatically intercepts without needing to pass the normal test.",                                                                                                                           StarPlayerSkill.Yoink,                  ["Dirty Player", "Dodge", "Loner (4+)", "Pogo", "Right Stuff", "Sprint", "Stunty", "Sure Feet"]),
            new("Skitter Stab-Stab",            "Master Assassin",              "Once per game, when Skitter performs a Stab, he may re-roll the Armour roll.",                                                                                                                                                                                           StarPlayerSkill.MasterAssassin,         ["Dodge", "Loner (4+)", "Prehensile Tail", "Shadowing", "Stab"]),
            new("Skrorg Snowpelt",              "Pump Up the Crowd",            "Once per game, when Skrorg causes a Casualty via a Block, his coach gains one Team Re-roll until the end of the current Drive. If unused by end of Drive, it is lost.",                                                                                                  StarPlayerSkill.PumpUpTheCrowd,         ["Block", "Claws", "Disturbing Presence", "Juggernaut", "Loner (4+)", "Mighty Blow"]),
            new("Skrull Halfheight",            "Strong Passing Game",          "Once per game, when Skrull makes a Pass, he may boost the Agility test result by up to his ST value, to a maximum result of 6.",                                                                                                                                         StarPlayerSkill.StrongPassingGame,      ["Accurate", "Loner (4+)", "Nerves Of Steel", "Pass", "Regeneration", "Sure Hands", "Thick Skull"]),
            new("The Black Gobbo",              "Sneakiest of the Lot",         "Your team may declare two Foul Actions per turn, but one of them must be performed by the Black Gobbo himself.",                                                                                                                                                          StarPlayerSkill.SneakiestOfTheLot,     ["Bombardier", "Disturbing Presence", "Dodge", "Loner (3+)", "Sidestep", "Sneaky Git", "Stab", "Stunty"]),
            new("Thorsson Stoutmead",           "Beer Barrel Bash!",            "Once per Drive at activation start, pick an opponent within 3 squares and roll a D6: on 3+ they're knocked down; on 2 nothing happens; on 1 Thorsson falls over instead. His activation ends immediately after.",                                                        StarPlayerSkill.BeerBarrelBash,         ["Block", "Drunkard", "Loner (4+)", "Thick Skull"]),
            new("Valen Swift",                  "Working in Tandem",            "Must be hired alongside Lucien Swift. If Lucien blocks an opponent who is also Marked by Valen, Lucien may re-roll one Block die.",                                                                                                                                       StarPlayerSkill.WorkingInTandem,        ["Accurate", "Loner (4+)", "Nerves Of Steel", "Pass", "Safe Pass", "Sure Hands"]),
            new("Varag Ghoul-Chewer",           "Krump and Smash",              "Once per game, when Varag knocks down an opponent with a Block, re-roll the Armour roll.",                                                                                                                                                                                StarPlayerSkill.KrumpAndSmash,          ["Block", "Hatred (Undead)", "Jump Up", "Loner (4+)", "Mighty Blow", "Thick Skull", "Unsteady"]),
            new("Wilhelm Chaney",               "Savage Mauling",               "Once per game, when Wilhelm makes an Injury roll against an opponent, he may re-roll the result.",                                                                                                                                                                        StarPlayerSkill.SavageMauling,          ["Catch", "Claws", "Frenzy", "Loner (4+)", "Regeneration", "Wrestle"]),
            new("Withergrasp Doubledrool",      "Watch Out!",                   "The first time each Drive that Withergrasp is targeted by a Block action, he counts as having the Dodge skill.",                                                                                                                                                          StarPlayerSkill.WatchOut,               ["Foul Appearance", "Loner (4+)", "Prehensile Tail", "Tackle", "Tentacles", "Two Heads", "Wrestle"]),
            new("Zolcath the Zoat",             "Excuse Me, Are You a Zoat?",   "Once per game when activated, Zolcath selects an opposition player within 3 squares. That player immediately becomes Distracted.",                                                                                                                                       StarPlayerSkill.ExcuseMeAreYouAZoat,   ["Disturbing Presence", "Juggernaut", "Loner (4+)", "Mighty Blow", "Prehensile Tail", "Regeneration", "Sure Feet"]),
        };

        public static IReadOnlyDictionary<string, StarPlayerRule> ByStarPlayer { get; } =
            All.ToDictionary(r => r.StarPlayer);

        public static IReadOnlyDictionary<string, StarPlayerRule> ByRuleName { get; } =
            All.GroupBy(r => r.RuleName)
               .ToDictionary(g => g.Key, g => g.First());
    }
}
