using System.ComponentModel;

namespace ActionCalculator.Models
{
    public enum StarPlayer
    {
        [Description("Akhorne the Squirrel")]              [ShortName("Akhorne")]     AkhorneTheSquirrel = 1,
        [Description("Anqi Panqi")]                        [ShortName("Anqi")]        AnqiPanqi,
        [Description("Barik Farblast")]                    [ShortName("Barik")]       BarikFarblast,
        [Description("Bilerot Vomitflesh")]                [ShortName("Bilerot")]     BilerotVomitflesh,
        [Description("Boa Kon'ssstriktr")]                 [ShortName("Boa")]         BoaKonssstriktr,
        [Description("Bomber Dribblesnot")]                [ShortName("Bomber")]      BomberDribblesnot,
        [Description("Captain Karina von Riesz")]          [ShortName("Karina")]      CaptainKarinaVonRiesz,
        [Description("Cindy Piewhistle")]                  [ShortName("Cindy")]       CindyPiewhistle,
        [Description("Count Luthor von Drakenborg")]       [ShortName("Luthor")]      CountLuthorVonDrakenborg,
        [Description("Crumbleberry")]                      [ShortName("Crumble")]     Crumbleberry,
        [Description("Dribl")]                             [ShortName("Dribl")]       Dribl,
        [Description("Drull")]                             [ShortName("Drull")]       Drull,
        [Description("Eldril Sidewinder")]                 [ShortName("Eldril")]      EldrilSidewinder,
        [Description("Estelle la Veneaux")]                [ShortName("Estelle")]     EstelleLaVeneaux,
        [Description("Frank 'N' Stein")]                   [ShortName("Frank")]       FrankNStein,
        [Description("Fungus the Loon")]                   [ShortName("Fungus")]      FungusTheLoon,
        [Description("Glart Smarshrip")]                   [ShortName("Glart")]       GlartSmarshrip,
        [Description("Gloriel Summerbloom")]               [ShortName("Gloriel")]     GlorielSummerbloom,
        [Description("Glotl Stop")]                        [ShortName("Glotl")]       GlotlStop,
        [Description("Grak")]                              [ShortName("Grak")]        Grak,
        [Description("Grashnak Blackhoof")]                [ShortName("Grashnak")]    GrashnakBlackhoof,
        [Description("Gretchen Wächter")]                  [ShortName("Gretchen")]    GretchenWachter,
        [Description("Griff Oberwald")]                    [ShortName("Griff")]       GriffOberwald,
        [Description("Grombrindal, the White Dwarf")]      [ShortName("Grom")]        GrombrindaTheWhiteDwarf,
        [Description("Guffle Pusmaw")]                     [ShortName("Guffle")]      GufflePusmaw,
        [Description("H'thark The Unstoppable")]           [ShortName("H'thark")]     HtharkTheUnstoppable,
        [Description("Hakflem Skuttlespike")]              [ShortName("Hakflem")]     HakflemSkuttlespike,
        [Description("Helmut Wulf")]                       [ShortName("Helmut")]      HelmutWulf,
        [Description("Ivan 'the Animal' Deathshroud")]     [ShortName("Ivan")]        IvanTheAnimalDeathshroud,
        [Description("Ivar Eriksson")]                     [ShortName("Ivar")]        IvarEriksson,
        [Description("Jeremiah Kool")]                     [ShortName("Jeremiah")]    JeremiahKool,
        [Description("Jordell Freshbreeze")]               [ShortName("Jordell")]     JordellFreshbreeze,
        [Description("Josef Bugman")]                      [ShortName("Josef")]       JosefBugman,
        [Description("Karla Von Kill")]                    [ShortName("Karla")]       KarlaVonKill,
        [Description("Kiroth Krakeneye")]                  [ShortName("Kiroth")]      KirothKrakeneye,
        [Description("Kreek, \"The Verminator\" Rustgouger")] [ShortName("Kreek")]   KreekTheVerminatorRustgouger,
        [Description("Lord Borak")]                        [ShortName("Borak")]       LordBorak,
        [Description("Lucien Swift")]                      [ShortName("Lucien")]      LucienSwift,
        [Description("Max Spleenripper")]                  [ShortName("Max")]         MaxSpleenripper,
        [Description("Mighty Zug")]                        [ShortName("Zug")]         MightyZug,
        [Description("Morg 'n' Thorg")]                    [ShortName("Morg")]        MorgNThorg,
        [Description("Nobbla Blackwart")]                  [ShortName("Nobbla")]      NobblaBlackwart,
        [Description("Puggy Baconbreath")]                 [ShortName("Puggy")]       PuggyBaconbreath,
        [Description("Rashnack Backstabber")]              [ShortName("Rashnack")]    RashnackBackstabber,
        [Description("Ripper Bolgrot")]                    [ShortName("Ripper")]      RipperBolgrot,
        [Description("Roxanna Darknail")]                  [ShortName("Roxanna")]     RoxannaDarknail,
        [Description("Rumbelow Sheepskin")]                [ShortName("Rumbelow")]    RumbelowSheepskin,
        [Description("Scyla Anfingrimm")]                  [ShortName("Scyla")]       ScylaAnfingrimm,
        [Description("Scrappa Sorehead")]                  [ShortName("Scrappa")]     ScrappaSorehead,
        [Description("Skitter Stab-Stab")]                 [ShortName("Skitter")]     SkitterStabStab,
        [Description("Skrorg Snowpelt")]                   [ShortName("Skrorg")]      SkrorgSnowpelt,
        [Description("Skrull Halfheight")]                 [ShortName("Skrull")]      SkrullHalfheight,
        [Description("The Black Gobbo")]                   [ShortName("Gobbo")]       TheBlackGobbo,
        [Description("Thorsson Stoutmead")]                [ShortName("Thorsson")]    ThorssonStoutmead,
        [Description("Valen Swift")]                       [ShortName("Valen")]       ValenSwift,
        [Description("Varag Ghoul-Chewer")]                [ShortName("Varag")]       VaragGhoulChewer,
        [Description("Wilhelm Chaney")]                    [ShortName("Wilhelm")]     WilhelmChaney,
        [Description("Withergrasp Doubledrool")]           [ShortName("Wither")]      WithergraspDoubledrool,
        [Description("Zolcath the Zoat")]                  [ShortName("Zolcath")]     ZolcathTheZoat,
    }
}
